version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  app:
    container_name: app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /home/www
    volumes: 
      - ./:/home/www
  cron:
    container_name: cron
    build:
      context: ./docker/cron
      dockerfile: Dockerfile
    working_dir: /home/www
    volumes: 
      - ./:/home/www
  supervisor:
    container_name: supervisor
    build:
      context: ./docker/supervisor
      dockerfile: Dockerfile
    working_dir: /home/www
    volumes: 
      - ./:/home/www
  web:    
    container_name: web
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /home/www
    volumes:
      - ./:/home/www
    ports:
      - 80:80
    depends_on: 
      - app
      - redis