version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  app:
    container_name: app
    build: 
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www
    volumes: 
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:    
    container_name: web
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    depends_on: 
      - app
      - database
      - redis
  database:
    image: mysql:5.7.21
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata:
