version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  app:
    container_name: app
    image: quanca/laravelapp
    build:      
      context: .
      dockerfile: ./docker/php/Dockerfile.prod
    working_dir: /var/www
  cron:
    container_name: cron
    image: quanca/laravelcron
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile.prod
    working_dir: /var/www
  supervisor:
    container_name: supervisor
    image: quanca/laravelsupervisor
    build:
      context: .
      dockerfile: ./docker/supervisor/Dockerfile.prod
    working_dir: /var/www
  web:    
    container_name: web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.prod
    working_dir: /var/www
    ports:
      - 80:80
    depends_on: 
      - app
      - redis